AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  IAM Automation Lab: Creates IAM Users, Groups, Permissions, and stores a temporary password in Secrets Manager.

Parameters:
  InitialPassword:
    Type: String
    Description: Temporary password for IAM users
    NoEcho: true
    Default: '{{resolve:secretsmanager:IAMTemporaryPassword:SecretString:password}}'

Resources:

  # Secrets Manager Secret
  IAMTempPasswordSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: IAMTemporaryPassword
      Description: Temporary password for IAM users
      GenerateSecretString:
        SecretStringTemplate: '{"username": "placeholder"}'
        GenerateStringKey: password
        PasswordLength: 16

  # IAM Group for S3
  S3Group:
    Type: AWS::IAM::Group
    Properties:
      GroupName: dev-collins-S3Group
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/IAMUserChangePassword

  # IAM Group for EC2
  EC2Group:
    Type: AWS::IAM::Group
    Properties:
      GroupName: dev-collins-EC2Group
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
        - arn:aws:iam::aws:policy/IAMUserChangePassword

  # s3-user IAM user
  S3User:
    Type: AWS::IAM::User
    Properties:
      UserName: s3-user-collins
      Groups:
        - !Ref S3Group
      LoginProfile:
        Password: !Ref InitialPassword
        PasswordResetRequired: true

  # ec2-user IAM user
  EC2User:
    Type: AWS::IAM::User
    Properties:
      UserName: ec2-user-collins
      Groups:
        - !Ref EC2Group
      LoginProfile:
        Password: !Ref InitialPassword
        PasswordResetRequired: true

Outputs:
  TempPasswordSecretARN:
    Description: ARN of the Secrets Manager secret with the temporary password
    Value: !Ref IAMTempPasswordSecret

  S3UserConsole:
    Description: s3 user use account-specific sign-in URL
    Value: !Sub "https://${AWS::AccountId}.signin.aws.amazon.com/console"

  EC2UserConsole:
    Description: ec2 user account-specific sign-in URL
    Value: !Sub "https://${AWS::AccountId}.signin.aws.amazon.com/console"